---
- hosts: all
  vars:
    nagios_version: '4.4.5'
    nagios_plugin_version: '2.2.1'
    packages_redhat:
      - autoconf 
      - gcc 
      - glibc 
      - glibc-common
      - make 
      - wget 
      - unzip 
      - httpd 
      - php 
      - gd 
      - gd-devel
      - perl
      - net-snmp
      - net-snmp-utils
      - openssl-devel 
      - gettext
      - automake
      - postfix
      - epel-release
      - perl-Net-SNMP
    nagios_code_location: /tmp/nagioscore.tar.gz
    nagios_plugin_location: /tmp/nagios-plugins.tar.gz
  become: yes
  tasks:
    - name: fail for unsupported os
      fail:
        msg: This playbook runs only on redhat
      when: ansible_facts['os_family'] == "CentOS"
    - name: install packages for redhat
      yum:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop: "{{ packages_redhat }}"
      tags:
        - nagios
    - name: Download the source to temp folder
      get_url:
        dest: "{{ nagios_code_location }}"
        url: "https://github.com/NagiosEnterprises/nagioscore/archive/nagios-{{ nagios_version }}.tar.gz"
      tags:
        - nagios
    - name: untar the code
      unarchive:
        src: "{{ nagios_code_location }}"
        dest: "/tmp/"
        remote_src: yes
      tags:
        - nagios
    - name: Compile Code
      shell:
        cmd: sudo ./configure && sudo make all > makeoutput.log
      args:
        chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/"
      tags:
        - nagios
    - name: Create User and Group
      shell:
        cmd: sudo make install-groups-users > installgroups.log && sudo usermod -a -G nagios apache > usermod.log
      args:
        chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/"
      tags:
        - nagios
    - name: Install Binaries
      shell:
        cmd: sudo make install > makeinstall.log
      args:
        chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/"
      tags:
        - nagios
    - name: Install Service / Daemon
      shell:
        cmd: sudo make install-daemoninit > daemoninit.log
      args:
        chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/"
      tags:
        - nagios
    - name: Install Command Mode
      shell:
        cmd: sudo make install-commandmode > commandmode.log
      args:
        chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/"
      tags:
        - nagios
    - name: Install Configuration Files
      shell:
        cmd: sudo make install-config > config.log
      args:
        chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/"
      tags:
        - nagios
    - name: Install redhat Config Files
      shell:
        cmd: sudo make install-webconf > webconf.log 
      args:
        chdir: "/tmp/nagioscore-nagios-{{ nagios_version }}/"
      tags:
        - nagios
    - name: Install latest passlib with pip
      pip: 
        name: passlib
        state: present
      tags:
        - nagios
    - name: Create nagiosadmin user account
      htpasswd:
        path: /usr/local/nagios/etc/htpasswd.users # required. Path to the file that contains the usernames and passwords
        name: nagiosadmin # required. User name to add or remove
        password: nagiosadmin # not required. Password associated with user.,Must be specified if user does not exist yet.
      tags:
        - nagios
    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: true
      tags:
        - nagios
    - name: start nagios
      service:
        name: nagios
        state: started
        enabled: true
      tags:
        - nagios
    - name: Download the plugin to temp folder
      get_url:
        dest: "{{ nagios_plugin_location }}"
        url: "https://github.com/nagios-plugins/nagios-plugins/archive/release-{{ nagios_plugin_version }}.tar.gz"
      tags:
        - plugin
    - name: untar the plugin code
      unarchive:
        src: "{{ nagios_plugin_location }}"
        dest: "/tmp/"
        remote_src: yes
      tags:
        - plugin
    - name: Compile + Install
      shell:
        cmd:  cd /tmp/nagios-plugins-release-2.2.1/ && sudo ./tools/setup > setup.log && sudo ./configure > configue.log && sudo make > make.log && sudo make install
      args:
        chdir: "/tmp/nagios-plugins-release-{{ nagios_plugin_version }}/"
      tags:
        - plugin
    - name: restart nagios
      service:
        name: nagios
        state: restarted
      tags:
        - plugin
    - name: restart httpd
      service:
        name: httpd
        state: restarted
      tags:
        - plugin
   

